site_name: LiLuan's Blog 
site_url: https://mkdocs.zimoapps.com
site_description: Easily type math in your webapp
site_author: liluan
# site_favicon: http://mathquill.com/favicon.ico # 图标

repo_url: https://github.com/zimocode/mkdocs-docs-zh/
edit_uri: ""

nav:
  - 主页: index.md
  - 我的笔记: MyPC.md
  - 文本编辑:
    - MkDocks用法指南: text/MkDocs.md
    - MarkDown用法指南: text/MarkDown.md
    - LaTeX用法指南: text/LatexNote.md
    - Pandoc用法指南: text/Pandoc.md
  - 编程:
    - C/C++: code/C.md
    - Python: code/Python.md
    - Java: code/java.md
    - Matlab: code/matlab.md
  - 社会:
    - 周易: skill/god.md
  - 关于:
    - 发行说明: about/release-notes.md
    - 贡献: about/contributing.md
    - 许可: about/license.md

theme: readthedocs

markdown_extensions:
  # - toc:
  #   permalink: True
  - admonition
  # - def_list
  # - mdx_gh_links:
  #   user: mkdocs
  #   repo: mkdocs

plugins:
  - search

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>. <a href="http://www.beian.miit.gov.cn" target="_blank">蜀ICP备19036239号</a>

# google_analytics: ['UA-73742753-3', 'docs.mathquill.com']
